require 'rake/clean'
require 'rubygems'
require 'maruku'

CLEAN.include('resume.tex', '*.log', '*.out', '*.aux')
CLOBBER.include('*.pdf', '*.html')

pdflatex = ENV.has_key?('OS') && ENV['OS'] == 'Windows_NT' ?
           'C:\\Tools\\miktex\\miktex\\bin\\pdflatex.exe --trace ' : '/usr/local/texlive/2012/bin/x86_64-darwin/pdflatex'

task :default => ['resume.pdf', 'cover.pdf', 'resume.html']

rule '.pdf' => '.tex' do |t|
  sh "#{pdflatex} #{t.source}"
end

rule '.tex' => '.md' do |t|
  text = read_all t.source
  doc = Maruku.new(text)
  pdf = doc.to_latex_document
  File.new(t.name, 'w').puts pdf
end

rule '.html' => '.md' do |t|
  text = read_all t.source
  doc = Maruku.new(text)
  pdf = doc.to_html_document
  File.new(t.name, 'w').puts pdf
end

def read_all(filename)
  all = ''
  File.open(filename).each_line do |line|
    all += line
  end

  return all
end
